### ISSUE TITLE
Broken Reddit Link in Footer

### ISSUE THREAD

**Issue by ABOTlegacy** [TheBastionBot/Bastion-Website#8]
![brokenredditlink](https://user-images.githubusercontent.com/5065837/48512179-78506e00-e81e-11e8-9434-02db969a3199.png)

At the bottom of the page, in the footer, the Reddit link is currently broken.

Looks like a copy and paste error from the twitter link.

Otherwise the site looks awesome! Great Job!

**Comment by k3rn31p4nic** [comment]
Thanks for the report. Will fix it ASAP.

**Comment by k3rn31p4nic** [comment]
Fixed it in https://github.com/TheBastionBot/thebastionbot.github.io/commit/6d28a249d525dbb1a660fc9e69ed272bb1df1318
